### ISSUE TITLE
LICENSE file is missing

### ISSUE THREAD

**Issue by jupe** [lklepner/socket.io-adapter-mongo#6]
Could you add LICENSE file to root folder to ensure that automation tools understand which license is used in this module, thanks :)

**Comment by lklepner** [comment]
Would you mind submitting a PR for this? The most permissive / least restrictive license seems appropriate.

**Comment by jupe** [comment]
easiest way to get it here is using github templates, see  instructions:
https://help.github.com/articles/adding-a-license-to-a-repository
:)

**Comment by lklepner** [comment]
what license do you recommend?

**Comment by lklepner** [comment]
I went with MIT - its in there now

**Comment by jupe** [comment]
Thanks 👍. Might be that some tools like dependency-ci doesn’t recognize it until its included in release..
