### ISSUE TITLE
new release request

### ISSUE THREAD

**Issue by jupe** [lklepner/socket.io-adapter-mongo#7]
Seems that https://dependencyci.com is not happy because LICENSE file is not in release, so please create patch release with LICENSE file.

**Comment by jupe** [comment]
ping - please could you create new release?

**Comment by jupe** [comment]
ping

**Comment by lklepner** [comment]
Try it now - I just published 2.0.1

**Comment by jupe** [comment]
https://libraries.io/npm/socket.io-adapter-mongo
yes now it detects license. Thanks.
